-- =============================================
-- Seed data for Calisteniapp
-- Run this AFTER schema.sql
-- =============================================

-- Insert exercises with Spanish translations and video resources
INSERT INTO "Exercise" (id, name, description, image, muscle_group, difficulty, resources) VALUES
(1, 'Flexiones', 'Ejercicio basico para pecho, hombros y triceps. Colocate en posicion de plancha con las manos a la altura de los hombros y baja el cuerpo hasta que el pecho casi toque el suelo.', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&q=80', ARRAY['chest', 'shoulders', 'triceps'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=IODxDxX7oi4", "title": "Push Up Tutorial"}]'::jsonb),
(2, 'Dominadas', 'Ejercicio fundamental para espalda y biceps. Cuelgate de una barra con agarre prono y eleva tu cuerpo hasta que la barbilla supere la barra.', 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=800&q=80', ARRAY['back', 'biceps'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=30NjUye3y6Q", "title": "Pull Up Tutorial"}]'::jsonb),
(3, 'Sentadilla', 'Sentadilla basica para piernas. Baja las caderas como si fueras a sentarte manteniendo la espalda recta y las rodillas alineadas con los pies.', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80', ARRAY['legs', 'glutes'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=zJBLDJMJiDE", "title": "Full Squat Tutorial"}]'::jsonb),
(4, 'Fondos', 'Fondos en paralelas para triceps y pecho. Sujetate en barras paralelas y baja el cuerpo flexionando los codos hasta formar un angulo de 90 grados.', 'https://images.unsplash.com/photo-1598266663439-2056e6900339?w=800&q=80', ARRAY['triceps', 'chest', 'shoulders'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=2z8JmcrW-As", "title": "Dip Tutorial"}]'::jsonb),
(5, 'Plancha', 'Plancha isometrica para core. Manten el cuerpo recto apoyado sobre antebrazos y puntas de los pies, activando el abdomen.', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=800&q=80', ARRAY['core', 'shoulders'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=44ScXWFaVBs&feature=youtu.be&t=10s", "title": "Plank Tutorial"}]'::jsonb),
(6, 'Muscle Up', 'Ejercicio avanzado que combina dominada y fondo. Realiza una dominada explosiva y transiciona sobre la barra para completar un fondo.', 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&q=80', ARRAY['back', 'chest', 'triceps', 'shoulders'], 5, '[{"type": "video", "url": "https://www.youtube.com/watch?v=2FZ9t2vl1kc", "title": "Muscle Up Tutorial"}]'::jsonb),
(7, 'Sentadilla Pistola', 'Sentadilla a una pierna. Baja completamente sobre una pierna mientras mantienes la otra extendida al frente.', 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=800&q=80', ARRAY['legs', 'glutes', 'core'], 4, '[{"type": "video", "url": "https://youtu.be/0SN8ZaxOBpA?t=30s", "title": "Pistol Squat Tutorial"}]'::jsonb),
(8, 'Flexion en Pino', 'Flexiones en posicion de pino. Realiza una flexion mientras estas en posicion invertida contra una pared o en equilibrio libre.', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80', ARRAY['shoulders', 'triceps', 'core'], 5, '[{"type": "video", "url": "https://youtu.be/CDCHdKDx0UY?t=69", "title": "Handstand Push Up Tutorial"}]'::jsonb),
(9, 'L-Sit', 'Posicion isometrica de L. Sientate con las piernas extendidas y eleva todo el cuerpo del suelo usando solo las manos.', 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=800&q=80', ARRAY['core', 'triceps', 'shoulders'], 3, '[{"type": "video", "url": "https://youtu.be/4bzLorsqBNc?t=17", "title": "L-Sit Tutorial"}]'::jsonb),
(10, 'Remo Australiano', 'Dominada horizontal para principiantes. Cuelgate de una barra baja con los pies en el suelo y tira del pecho hacia la barra.', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80', ARRAY['back', 'biceps'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=JkG2aQO7sF8", "title": "Row Tutorial"}]'::jsonb),
(11, 'Flexion Diamante', 'Flexiones con manos juntas formando un diamante. Mayor enfasis en triceps que las flexiones regulares.', 'https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?w=800&q=80', ARRAY['triceps', 'chest'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=_4EGPVJuqfA", "title": "Diamond Push Up Tutorial"}]'::jsonb),
(12, 'Dominadas Supinas', 'Dominada con agarre supino. Similar a la dominada pero con las palmas mirando hacia ti, mayor enfasis en biceps.', 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=800&q=80', ARRAY['biceps', 'back'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=30NjUye3y6Q", "title": "Chin Up Tutorial"}]'::jsonb),
(13, 'Burpee', 'Ejercicio de cuerpo completo. Combina una sentadilla, plancha, flexion y salto en un movimiento continuo.', 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=800&q=80', ARRAY['legs', 'chest', 'core', 'shoulders'], 2, '[]'::jsonb),
(14, 'Front Lever', 'Posicion horizontal colgado de la barra. Manten el cuerpo completamente horizontal mirando hacia arriba.', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80', ARRAY['back', 'core', 'shoulders'], 5, '[{"type": "video", "url": "https://youtu.be/ZqCLG0hiRco?t=8", "title": "Front Lever Tutorial"}]'::jsonb),
(15, 'Back Lever', 'Posicion horizontal invertida en la barra. Manten el cuerpo horizontal mirando hacia el suelo.', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80', ARRAY['shoulders', 'back', 'core'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=HXaG8mJmSnU", "title": "Back Lever Tutorial"}]'::jsonb),
(16, 'Bandera Humana', 'Bandera humana. Manten el cuerpo horizontal agarrado a un poste vertical.', 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80', ARRAY['core', 'shoulders', 'back'], 5, '[{"type": "video", "url": "https://youtu.be/lczvDH9Fze4?t=204", "title": "Human Flag Tutorial"}]'::jsonb),
(17, 'Flexion Arquero', 'Flexion arquero. Una mano cerca del cuerpo mientras la otra se extiende lateralmente.', 'https://images.unsplash.com/photo-1616803689943-5601631c7fec?w=800&q=80', ARRAY['chest', 'triceps', 'shoulders'], 3, '[{"type": "video", "url": "https://youtu.be/dyDBGkJWgZE?list=PLBF8536CA2AB746EC&t=19", "title": "Archer Push Up Tutorial"}]'::jsonb),
(18, 'Tuck Planche', 'Planche con rodillas recogidas. Equilibrio sobre las manos con el cuerpo elevado y rodillas al pecho.', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80', ARRAY['shoulders', 'chest', 'core'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=VFYZh24e0RI", "title": "Tuck Planche Tutorial"}]'::jsonb),
(19, 'Dragon Flag', 'Ejercicio avanzado de core. Acostado boca arriba, eleva las piernas y caderas manteniendo solo los hombros en contacto con el banco.', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80', ARRAY['core'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=moyFIvRrS0s", "title": "Dragon Flag Tutorial"}]'::jsonb),
(20, 'Elevacion de Piernas Colgado', 'Elevacion de piernas colgado. Cuelgate de una barra y eleva las piernas rectas hasta formar un angulo de 90 grados.', 'https://images.unsplash.com/photo-1597347316205-36f6c451902a?w=800&q=80', ARRAY['core'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=at_A-H6JTGk", "title": "Hanging Leg Raise Tutorial"}]'::jsonb),
(21, 'Flexion en Pared', 'Flexion contra la pared. El ejercicio mas basico de la progresion de flexiones, ideal para principiantes absolutos.', 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80', ARRAY['chest', 'shoulders', 'triceps'], 0, '[{"type": "video", "url": "https://youtu.be/6jm4R3K4sJA?t=34", "title": "Wall Plank Tutorial"}]'::jsonb),
(22, 'Flexion Inclinada', 'Flexion inclinada con manos en superficie elevada. Reduce la carga comparado con la flexion estandar.', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&q=80', ARRAY['chest', 'shoulders', 'triceps'], 0, '[{"type": "video", "url": "https://youtu.be/4dF1DOWzf20?t=3m56s", "title": "Incline Push Up Tutorial"}]'::jsonb),
(23, 'Flexion de Rodillas', 'Flexion con rodillas apoyadas. Version modificada que reduce la carga corporal en aproximadamente un 50%.', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&q=80', ARRAY['chest', 'shoulders', 'triceps'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=IODxDxX7oi4", "title": "Push Up Tutorial"}]'::jsonb),
(24, 'Flexion Abierta', 'Flexion con manos mas separadas que el ancho de hombros. Mayor enfasis en el pecho.', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&q=80', ARRAY['chest', 'shoulders'], 1, '[{"type": "video", "url": "http://www.youtube.com/watch?v=1yMRvsuk9Xg", "title": "Wide Push Up Tutorial"}]'::jsonb),
(25, 'Flexion a Una Mano', 'Flexion a una mano. Ejercicio avanzado que requiere gran fuerza y estabilidad del core.', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&q=80', ARRAY['chest', 'shoulders', 'triceps', 'core'], 5, '[{"type": "video", "url": "https://youtu.be/MlRCAJbwjMs?t=65", "title": "One Arm Push Up Tutorial"}]'::jsonb),
(26, 'Dominada Escapular', 'Activacion escapular colgado de la barra. Primer paso para construir fuerza de tiron.', 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=800&q=80', ARRAY['back', 'shoulders'], 0, '[{"type": "video", "url": "https://youtu.be/FgYoc4O-cio?t=1m21s", "title": "Scapular Pull Tutorial"}]'::jsonb),
(27, 'Dominada Negativa', 'Dominada negativa. Salta arriba y baja lentamente controlando el movimiento.', 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=800&q=80', ARRAY['back', 'biceps'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=gbPURTSxQLY", "title": "Pull Up Negative Tutorial"}]'::jsonb),
(28, 'Dominada con Banda', 'Dominada asistida con banda elastica. La banda reduce el peso corporal que debes levantar.', 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=800&q=80', ARRAY['back', 'biceps'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=30NjUye3y6Q", "title": "Pull Up Tutorial"}]'::jsonb),
(29, 'Dominada con Peso', 'Dominada con peso adicional. Progresion avanzada para aumentar la fuerza de tiron.', 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=800&q=80', ARRAY['back', 'biceps'], 3, '[{"type": "video", "url": "https://www.youtube.com/watch?v=30NjUye3y6Q", "title": "Weighted Pull Up Tutorial"}]'::jsonb),
(30, 'Sentadilla Asistida', 'Sentadilla asistida sujetandose de algo. Ideal para aprender la tecnica correcta.', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80', ARRAY['legs', 'glutes'], 0, '[{"type": "video", "url": "https://www.youtube.com/watch?v=OuR_Fp7AB0c", "title": "Assisted Squat Tutorial"}]'::jsonb),
(31, 'Sentadilla en Caja', 'Sentadilla a una caja o banco. Ayuda a controlar la profundidad y la tecnica.', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80', ARRAY['legs', 'glutes'], 0, '[{"type": "video", "url": "https://www.youtube.com/watch?v=zJBLDJMJiDE", "title": "Box Squat Tutorial"}]'::jsonb),
(32, 'Sentadilla Bulgara', 'Sentadilla bulgara con pie trasero elevado. Trabaja cada pierna de forma unilateral.', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80', ARRAY['legs', 'glutes', 'core'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=kkdmHTASZg8&feature=youtu.be&t=1m15s", "title": "Bulgarian Split Squat Tutorial"}]'::jsonb),
(33, 'Sentadilla Camaron', 'Sentadilla camaron. Variante avanzada de sentadilla a una pierna con la pierna trasera sujeta.', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80', ARRAY['legs', 'glutes', 'core'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=_FBuC-VPbRY", "title": "Shrimp Squat Tutorial"}]'::jsonb),
(34, 'Fondos en Banco', 'Fondos en banco. Version mas facil de los fondos usando un banco o silla.', 'https://images.unsplash.com/photo-1598266663439-2056e6900339?w=800&q=80', ARRAY['triceps', 'chest'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=jWHKAXYNKfw", "title": "Bench Dip Tutorial"}]'::jsonb),
(35, 'Fondos Asistidos', 'Fondos asistidos con banda o maquina. Reduce la carga corporal para construir fuerza.', 'https://images.unsplash.com/photo-1598266663439-2056e6900339?w=800&q=80', ARRAY['triceps', 'chest', 'shoulders'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=2z8JmcrW-As", "title": "Assisted Dip Tutorial"}]'::jsonb),
(36, 'Fondos en Anillas', 'Fondos en anillas. Requiere mayor estabilidad y fuerza que los fondos en paralelas.', 'https://images.unsplash.com/photo-1598266663439-2056e6900339?w=800&q=80', ARRAY['triceps', 'chest', 'shoulders', 'core'], 3, '[{"type": "video", "url": "https://www.youtube.com/watch?v=DaNedgnJjB0", "title": "Ring Dip Tutorial"}]'::jsonb),
(37, 'Fondos con Peso', 'Fondos con peso adicional. Progresion para aumentar la fuerza de empuje.', 'https://images.unsplash.com/photo-1598266663439-2056e6900339?w=800&q=80', ARRAY['triceps', 'chest', 'shoulders'], 3, '[{"type": "video", "url": "https://www.youtube.com/watch?v=2z8JmcrW-As", "title": "Weighted Dip Tutorial"}]'::jsonb),
(38, 'Plancha Inclinada', 'Plancha inclinada con manos en superficie elevada. Version mas facil de la plancha.', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=800&q=80', ARRAY['core'], 0, '[{"type": "video", "url": "https://youtu.be/6jm4R3K4sJA?t=34", "title": "Incline Plank Tutorial"}]'::jsonb),
(39, 'Plancha Lateral', 'Plancha lateral. Trabaja los oblicuos y la estabilidad lateral del core.', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=800&q=80', ARRAY['core', 'shoulders'], 2, '[{"type": "video", "url": "https://youtu.be/44ScXWFaVBs?t=74", "title": "Side Plank Tutorial"}]'::jsonb),
(40, 'Plancha con Elevacion de Pierna', 'Plancha con elevacion de pierna. Aumenta la demanda de estabilidad del core.', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=800&q=80', ARRAY['core', 'shoulders', 'glutes'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=44ScXWFaVBs&feature=youtu.be&t=10s", "title": "Plank Leg Lift Tutorial"}]'::jsonb),
(41, 'Dominada Alta', 'Dominada alta llevando la barra al pecho o mas abajo. Prepara para el muscle up.', 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&q=80', ARRAY['back', 'biceps', 'shoulders'], 3, '[{"type": "video", "url": "https://www.youtube.com/watch?v=PmdNNN8nLGI", "title": "C2B Pull Up Tutorial"}]'::jsonb),
(42, 'Dominada Explosiva', 'Dominada explosiva con fase de vuelo. Desarrolla la potencia necesaria para el muscle up.', 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&q=80', ARRAY['back', 'biceps', 'shoulders'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=2FZ9t2vl1kc", "title": "Explosive Pull Up Tutorial"}]'::jsonb),
(43, 'L-Sit Recogido', 'L-Sit con rodillas recogidas. Primera progresion hacia el L-Sit completo.', 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=800&q=80', ARRAY['core', 'triceps'], 2, '[{"type": "video", "url": "https://youtu.be/IUZJoSP66HI?t=178", "title": "Tuck L-Sit Tutorial"}]'::jsonb),
(44, 'V-Sit', 'Posicion en V con piernas elevadas por encima de la horizontal. Progresion avanzada del L-Sit.', 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=800&q=80', ARRAY['core', 'triceps', 'shoulders'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=GbZeD4q_cSE", "title": "V-Sit Tutorial"}]'::jsonb),
(45, 'Flexion Pike', 'Flexion en pike. Simula el movimiento de la flexion en pino con menos carga.', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80', ARRAY['shoulders', 'triceps'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=1Jjjyp4uhks#t=26s", "title": "Pike Push Up Tutorial"}]'::jsonb),
(46, 'Flexion Pike Elevada', 'Flexion pike con pies elevados. Mayor carga en los hombros que el pike normal.', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80', ARRAY['shoulders', 'triceps', 'core'], 3, '[{"type": "video", "url": "https://www.youtube.com/watch?v=ZnsLpLhywgk&feature=youtu.be&t=50", "title": "Decline Pike Push Up Tutorial"}]'::jsonb),
(47, 'Flexion en Pino contra Pared', 'Flexion en pino contra la pared. Version asistida de la flexion en pino libre.', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80', ARRAY['shoulders', 'triceps', 'core'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=r-aiCMOOhNQ", "title": "Wall Handstand Push Up Tutorial"}]'::jsonb),
(48, 'Dead Bug', 'Ejercicio de core tumbado boca arriba moviendo brazos y piernas de forma alterna.', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=800&q=80', ARRAY['core'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=44ScXWFaVBs&feature=youtu.be&t=10s", "title": "Dead Bug Tutorial"}]'::jsonb),
(49, 'Hollow Body Hold', 'Posicion hollow con espalda baja pegada al suelo. Fundamental para gimnasia.', 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=800&q=80', ARRAY['core'], 2, '[{"type": "video", "url": "https://youtu.be/XzQe1S91Fr0?t=11", "title": "Hollow Hold Tutorial"}]'::jsonb),
(50, 'Elevacion de Rodillas', 'Elevacion de rodillas colgado. Version mas facil de la elevacion de piernas.', 'https://images.unsplash.com/photo-1597347316205-36f6c451902a?w=800&q=80', ARRAY['core'], 1, '[{"type": "video", "url": "https://www.youtube.com/watch?v=at_A-H6JTGk", "title": "Knee Raise Tutorial"}]'::jsonb),
(51, 'Toes to Bar', 'Llevar los pies a la barra colgado. Progresion avanzada de la elevacion de piernas.', 'https://images.unsplash.com/photo-1597347316205-36f6c451902a?w=800&q=80', ARRAY['core', 'back'], 3, '[{"type": "video", "url": "https://www.youtube.com/watch?v=at_A-H6JTGk", "title": "Toes to Bar Tutorial"}]'::jsonb),
(52, 'Tuck Front Lever', 'Front lever con rodillas recogidas al pecho. Primera progresion del front lever.', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80', ARRAY['back', 'core'], 3, '[{"type": "video", "url": "https://www.youtube.com/watch?v=JxlKAuD9gkA", "title": "Tuck Front Lever Tutorial"}]'::jsonb),
(53, 'Advanced Tuck Front Lever', 'Front lever con rodillas ligeramente extendidas. Progresion intermedia.', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80', ARRAY['back', 'core', 'shoulders'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=NicnELGtOSE", "title": "Advanced Tuck Front Lever Tutorial"}]'::jsonb),
(54, 'Straddle Front Lever', 'Front lever con piernas abiertas. Progresion avanzada hacia el full front lever.', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80', ARRAY['back', 'core', 'shoulders'], 5, '[{"type": "video", "url": "https://www.youtube.com/watch?v=PR-mHqduhtQ", "title": "Straddle Front Lever Tutorial"}]'::jsonb),
(55, 'Tuck Back Lever', 'Back lever con rodillas recogidas. Primera progresion del back lever.', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80', ARRAY['shoulders', 'back', 'core'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=LfyGMZh-Bz4", "title": "Tuck Back Lever Tutorial"}]'::jsonb),
(56, 'Straddle Back Lever', 'Back lever con piernas abiertas. Progresion hacia el full back lever.', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80', ARRAY['shoulders', 'back', 'core'], 3, '[{"type": "video", "url": "https://youtu.be/HXaG8mJmSnU?t=215", "title": "Straddle Back Lever Tutorial"}]'::jsonb),
(57, 'Planche Lean', 'Inclinacion de planche en posicion de flexion. Desarrolla fuerza de empuje.', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80', ARRAY['shoulders', 'chest', 'core'], 2, '[{"type": "video", "url": "https://youtu.be/liXL9oE3KzE?t=23", "title": "Planche Lean Tutorial"}]'::jsonb),
(58, 'Straddle Planche', 'Planche con piernas abiertas. Progresion avanzada hacia el full planche.', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80', ARRAY['shoulders', 'chest', 'core'], 5, '[{"type": "video", "url": "https://youtu.be/dHLYwZV96zw?t=294", "title": "Straddle Planche Tutorial"}]'::jsonb),
(59, 'Full Planche', 'Planche completa con piernas juntas y extendidas. Uno de los ejercicios mas dificiles.', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80', ARRAY['shoulders', 'chest', 'core'], 5, '[{"type": "video", "url": "https://www.youtube.com/watch?v=acij_BzyXRg", "title": "Full Planche Tutorial"}]'::jsonb),
(60, 'Curl Nordico', 'Ejercicio avanzado para isquiotibiales. Arrodillate con los pies anclados y baja el cuerpo hacia el suelo controlando el movimiento con los isquiotibiales.', 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=800&q=80', ARRAY['legs'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=d8AAPcYxPo8", "title": "Nordic Curl Tutorial"}]'::jsonb),
(61, 'Elevacion de Talones', 'Ejercicio basico para pantorrillas. De pie, eleva los talones del suelo contrayendo los gemelos y baja de forma controlada.', 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80', ARRAY['legs'], 0, '[{"type": "video", "url": "https://www.youtube.com/watch?v=487aR3A7HvM", "title": "Calf Raise Tutorial"}]'::jsonb),
(62, 'Limpiaparabrisas', 'Ejercicio avanzado de core rotacional. Colgado de la barra, eleva las piernas y rotalas de lado a lado manteniendo el control.', 'https://images.unsplash.com/photo-1597347316205-36f6c451902a?w=800&q=80', ARRAY['core'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=moyFIvRrS0s", "title": "Windshield Wipers Tutorial"}]'::jsonb),
(63, 'Colgado Aleman', 'Posicion de movilidad en anillas o barra baja. Cuelgate con los brazos detras del cuerpo estirando hombros y pecho.', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80', ARRAY['shoulders', 'chest'], 2, '[{"type": "video", "url": "https://www.youtube.com/watch?v=5KaDOUeMY98", "title": "German Hang Tutorial"}]'::jsonb),
(64, 'Pino', 'Equilibrio invertido sobre las manos. Manten el cuerpo recto y alineado mientras te sostienes boca abajo.', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80', ARRAY['shoulders', 'core'], 3, '[{"type": "video", "url": "https://www.youtube.com/watch?v=N3K9SMNKL7Y", "title": "Handstand Tutorial"}]'::jsonb),
(65, 'Flexion Pseudo Planche', 'Flexion con manos a la altura de las caderas y cuerpo inclinado hacia adelante. Prepara para la planche.', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&q=80', ARRAY['shoulders', 'chest', 'triceps', 'core'], 3, '[{"type": "video", "url": "http://www.youtube.com/watch?v=Cdmg0CfMZeo", "title": "Pseudo Planche Push Up Tutorial"}]'::jsonb),
(66, 'Dominada Arquero', 'Dominada unilateral con un brazo estirado lateralmente. Transfiere mas carga a un lado del cuerpo.', 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=800&q=80', ARRAY['back', 'biceps', 'core'], 4, '[{"type": "video", "url": "https://youtu.be/vdjWgw98EeI?t=1m52s", "title": "Archer Pull Up Tutorial"}]'::jsonb),
(67, 'Dominada a Una Mano', 'Dominada completa usando solo un brazo. Uno de los ejercicios de tiron mas avanzados de la calistenia.', 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=800&q=80', ARRAY['back', 'biceps', 'core'], 5, '[{"type": "video", "url": "https://www.youtube.com/watch?v=vdjWgw98EeI", "title": "One Arm Pull Up Tutorial"}]'::jsonb),
(68, 'Flexion con Palmada', 'Flexion pliometrica explosiva. Empuja con fuerza para elevar las manos del suelo y dar una palmada antes de aterrizar.', 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&q=80', ARRAY['chest', 'triceps', 'shoulders'], 3, '[{"type": "video", "url": "https://www.youtube.com/watch?v=IODxDxX7oi4", "title": "Clap Push Up Tutorial"}]'::jsonb),
(69, 'Fondos Coreanos', 'Fondos con las manos detras del cuerpo en una barra baja. Trabaja intensamente los triceps y hombros.', 'https://images.unsplash.com/photo-1598266663439-2056e6900339?w=800&q=80', ARRAY['triceps', 'shoulders', 'core'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=9mKyrPmmPt0", "title": "Korean Dip Tutorial"}]'::jsonb),
(70, 'Front Lever a Una Pierna', 'Front lever con una pierna extendida y la otra recogida. Progresion avanzada hacia el front lever completo.', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80', ARRAY['back', 'core'], 4, '[{"type": "video", "url": "https://www.youtube.com/watch?v=HzcWRdP78Wo", "title": "One Leg Front Lever Tutorial"}]'::jsonb),
(71, 'Planche Recogida Avanzada', 'Planche con caderas extendidas pero rodillas aun recogidas. Progresion entre el tuck planche y el straddle planche.', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80', ARRAY['shoulders', 'chest', 'core'], 4, '[{"type": "video", "url": "https://youtu.be/oLUHPdRF2vo?t=131", "title": "Advanced Tuck Planche Tutorial"}]'::jsonb)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    image = EXCLUDED.image,
    muscle_group = EXCLUDED.muscle_group,
    difficulty = EXCLUDED.difficulty,
    resources = EXCLUDED.resources;

-- Update equipment, category, and type for all exercises
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'push', type = 'dynamic' WHERE id = 1;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'pull', type = 'dynamic' WHERE id = 2;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'legs', type = 'dynamic' WHERE id = 3;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'push', type = 'dynamic' WHERE id = 4;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'core', type = 'isometric' WHERE id = 5;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar', 'rings'], category = 'pull', type = 'dynamic' WHERE id = 6;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'legs', type = 'dynamic' WHERE id = 7;
UPDATE "Exercise" SET equipment = ARRAY['wall'], category = 'push', type = 'dynamic' WHERE id = 8;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'core', type = 'isometric' WHERE id = 9;
UPDATE "Exercise" SET equipment = ARRAY['low_bar', 'rings'], category = 'pull', type = 'dynamic' WHERE id = 10;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'push', type = 'dynamic' WHERE id = 11;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'pull', type = 'dynamic' WHERE id = 12;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'full_body', type = 'plyometric' WHERE id = 13;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar', 'rings'], category = 'skill', type = 'isometric' WHERE id = 14;
UPDATE "Exercise" SET equipment = ARRAY['rings', 'pull_up_bar'], category = 'skill', type = 'isometric' WHERE id = 15;
UPDATE "Exercise" SET equipment = ARRAY['vertical_pole', 'stall_bars'], category = 'skill', type = 'isometric' WHERE id = 16;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'push', type = 'dynamic' WHERE id = 17;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'skill', type = 'isometric' WHERE id = 18;
UPDATE "Exercise" SET equipment = ARRAY['bench'], category = 'core', type = 'dynamic' WHERE id = 19;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'core', type = 'dynamic' WHERE id = 20;
UPDATE "Exercise" SET equipment = ARRAY['wall'], category = 'push', type = 'dynamic' WHERE id = 21;
UPDATE "Exercise" SET equipment = ARRAY['bench', 'elevated_surface'], category = 'push', type = 'dynamic' WHERE id = 22;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'push', type = 'dynamic' WHERE id = 23;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'push', type = 'dynamic' WHERE id = 24;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'push', type = 'dynamic' WHERE id = 25;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'pull', type = 'dynamic' WHERE id = 26;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'pull', type = 'dynamic' WHERE id = 27;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar', 'resistance_band'], category = 'pull', type = 'dynamic' WHERE id = 28;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar', 'weight_belt'], category = 'pull', type = 'dynamic' WHERE id = 29;
UPDATE "Exercise" SET equipment = ARRAY['support_surface'], category = 'legs', type = 'dynamic' WHERE id = 30;
UPDATE "Exercise" SET equipment = ARRAY['box', 'bench'], category = 'legs', type = 'dynamic' WHERE id = 31;
UPDATE "Exercise" SET equipment = ARRAY['bench'], category = 'legs', type = 'dynamic' WHERE id = 32;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'legs', type = 'dynamic' WHERE id = 33;
UPDATE "Exercise" SET equipment = ARRAY['bench'], category = 'push', type = 'dynamic' WHERE id = 34;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars', 'resistance_band'], category = 'push', type = 'dynamic' WHERE id = 35;
UPDATE "Exercise" SET equipment = ARRAY['rings'], category = 'push', type = 'dynamic' WHERE id = 36;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars', 'weight_belt'], category = 'push', type = 'dynamic' WHERE id = 37;
UPDATE "Exercise" SET equipment = ARRAY['elevated_surface'], category = 'core', type = 'isometric' WHERE id = 38;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'core', type = 'isometric' WHERE id = 39;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'core', type = 'isometric' WHERE id = 40;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'pull', type = 'dynamic' WHERE id = 41;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'pull', type = 'plyometric' WHERE id = 42;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'core', type = 'isometric' WHERE id = 43;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'core', type = 'isometric' WHERE id = 44;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'push', type = 'dynamic' WHERE id = 45;
UPDATE "Exercise" SET equipment = ARRAY['box', 'bench'], category = 'push', type = 'dynamic' WHERE id = 46;
UPDATE "Exercise" SET equipment = ARRAY['wall'], category = 'push', type = 'dynamic' WHERE id = 47;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'core', type = 'dynamic' WHERE id = 48;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'core', type = 'isometric' WHERE id = 49;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'core', type = 'dynamic' WHERE id = 50;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'core', type = 'dynamic' WHERE id = 51;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar', 'rings'], category = 'skill', type = 'isometric' WHERE id = 52;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar', 'rings'], category = 'skill', type = 'isometric' WHERE id = 53;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar', 'rings'], category = 'skill', type = 'isometric' WHERE id = 54;
UPDATE "Exercise" SET equipment = ARRAY['rings', 'pull_up_bar'], category = 'skill', type = 'isometric' WHERE id = 55;
UPDATE "Exercise" SET equipment = ARRAY['rings', 'pull_up_bar'], category = 'skill', type = 'isometric' WHERE id = 56;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'push', type = 'isometric' WHERE id = 57;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'skill', type = 'isometric' WHERE id = 58;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'skill', type = 'isometric' WHERE id = 59;
UPDATE "Exercise" SET equipment = ARRAY['anchor_point'], category = 'legs', type = 'dynamic' WHERE id = 60;
UPDATE "Exercise" SET equipment = ARRAY['step'], category = 'legs', type = 'dynamic' WHERE id = 61;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'core', type = 'dynamic' WHERE id = 62;
UPDATE "Exercise" SET equipment = ARRAY['rings', 'low_bar'], category = 'skill', type = 'isometric' WHERE id = 63;
UPDATE "Exercise" SET equipment = ARRAY['wall'], category = 'skill', type = 'isometric' WHERE id = 64;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'push', type = 'dynamic' WHERE id = 65;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'pull', type = 'dynamic' WHERE id = 66;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar'], category = 'pull', type = 'dynamic' WHERE id = 67;
UPDATE "Exercise" SET equipment = ARRAY['none'], category = 'push', type = 'plyometric' WHERE id = 68;
UPDATE "Exercise" SET equipment = ARRAY['low_bar', 'parallel_bars'], category = 'push', type = 'dynamic' WHERE id = 69;
UPDATE "Exercise" SET equipment = ARRAY['pull_up_bar', 'rings'], category = 'skill', type = 'isometric' WHERE id = 70;
UPDATE "Exercise" SET equipment = ARRAY['parallel_bars'], category = 'skill', type = 'isometric' WHERE id = 71;

-- Reset the sequence to continue from the last ID
SELECT setval('"Exercise_id_seq"', (SELECT MAX(id) FROM "Exercise"));
