import { Exercise, Workout } from '@/types/supabase';
import { WorkoutDetail, ExerciseWorkout } from '@/types/Workout';

export const mockExercises: (Exercise & { difficulty: number; muscle_group: string[] })[] = [
	{
		id: 1,
		name: 'Push Up',
		description: 'Ejercicio básico para pecho, hombros y tríceps. Colócate en posición de plancha con las manos a la altura de los hombros y baja el cuerpo hasta que el pecho casi toque el suelo.',
		image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&q=80',
		difficulty: 1,
		muscle_group: ['chest', 'shoulders', 'triceps'],
	},
	{
		id: 2,
		name: 'Pull Up',
		description: 'Ejercicio fundamental para espalda y bíceps. Cuélgate de una barra con agarre prono y eleva tu cuerpo hasta que la barbilla supere la barra.',
		image: 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=800&q=80',
		difficulty: 2,
		muscle_group: ['back', 'biceps'],
	},
	{
		id: 3,
		name: 'Squat',
		description: 'Sentadilla básica para piernas. Baja las caderas como si fueras a sentarte manteniendo la espalda recta y las rodillas alineadas con los pies.',
		image: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80',
		difficulty: 1,
		muscle_group: ['legs', 'glutes'],
	},
	{
		id: 4,
		name: 'Dips',
		description: 'Fondos en paralelas para tríceps y pecho. Sujétate en barras paralelas y baja el cuerpo flexionando los codos hasta formar un ángulo de 90 grados.',
		image: 'https://images.unsplash.com/photo-1598266663439-2056e6900339?w=800&q=80',
		difficulty: 2,
		muscle_group: ['triceps', 'chest', 'shoulders'],
	},
	{
		id: 5,
		name: 'Plank',
		description: 'Plancha isométrica para core. Mantén el cuerpo recto apoyado sobre antebrazos y puntas de los pies, activando el abdomen.',
		image: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=800&q=80',
		difficulty: 1,
		muscle_group: ['core', 'shoulders'],
	},
	{
		id: 6,
		name: 'Muscle Up',
		description: 'Ejercicio avanzado que combina dominada y fondo. Realiza una dominada explosiva y transiciona sobre la barra para completar un fondo.',
		image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&q=80',
		difficulty: 5,
		muscle_group: ['back', 'chest', 'triceps', 'shoulders'],
	},
	{
		id: 7,
		name: 'Pistol Squat',
		description: 'Sentadilla a una pierna. Baja completamente sobre una pierna mientras mantienes la otra extendida al frente.',
		image: 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=800&q=80',
		difficulty: 4,
		muscle_group: ['legs', 'glutes', 'core'],
	},
	{
		id: 8,
		name: 'Handstand Push Up',
		description: 'Flexiones en posición de pino. Realiza una flexión mientras estás en posición invertida contra una pared o en equilibrio libre.',
		image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
		difficulty: 5,
		muscle_group: ['shoulders', 'triceps', 'core'],
	},
	{
		id: 9,
		name: 'L-Sit',
		description: 'Posición isométrica de L. Siéntate con las piernas extendidas y eleva todo el cuerpo del suelo usando solo las manos.',
		image: 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=800&q=80',
		difficulty: 3,
		muscle_group: ['core', 'triceps', 'shoulders'],
	},
	{
		id: 10,
		name: 'Australian Pull Up',
		description: 'Dominada horizontal para principiantes. Cuélgate de una barra baja con los pies en el suelo y tira del pecho hacia la barra.',
		image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
		difficulty: 1,
		muscle_group: ['back', 'biceps'],
	},
	{
		id: 11,
		name: 'Diamond Push Up',
		description: 'Flexiones con manos juntas formando un diamante. Mayor énfasis en tríceps que las flexiones regulares.',
		image: 'https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?w=800&q=80',
		difficulty: 2,
		muscle_group: ['triceps', 'chest'],
	},
	{
		id: 12,
		name: 'Chin Up',
		description: 'Dominada con agarre supino. Similar al pull up pero con las palmas mirando hacia ti, mayor énfasis en bíceps.',
		image: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=800&q=80',
		difficulty: 2,
		muscle_group: ['biceps', 'back'],
	},
	{
		id: 13,
		name: 'Burpee',
		description: 'Ejercicio de cuerpo completo. Combina una sentadilla, plancha, flexión y salto en un movimiento continuo.',
		image: 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?w=800&q=80',
		difficulty: 2,
		muscle_group: ['legs', 'chest', 'core', 'shoulders'],
	},
	{
		id: 14,
		name: 'Front Lever',
		description: 'Posición horizontal colgado de la barra. Mantén el cuerpo completamente horizontal mirando hacia arriba.',
		image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
		difficulty: 5,
		muscle_group: ['back', 'core', 'shoulders'],
	},
	{
		id: 15,
		name: 'Back Lever',
		description: 'Posición horizontal invertida en la barra. Mantén el cuerpo horizontal mirando hacia el suelo.',
		image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
		difficulty: 4,
		muscle_group: ['shoulders', 'back', 'core'],
	},
	{
		id: 16,
		name: 'Human Flag',
		description: 'Bandera humana. Mantén el cuerpo horizontal agarrado a un poste vertical.',
		image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80',
		difficulty: 5,
		muscle_group: ['core', 'shoulders', 'back'],
	},
	{
		id: 17,
		name: 'Archer Push Up',
		description: 'Flexión arquero. Una mano cerca del cuerpo mientras la otra se extiende lateralmente.',
		image: 'https://images.unsplash.com/photo-1616803689943-5601631c7fec?w=800&q=80',
		difficulty: 3,
		muscle_group: ['chest', 'triceps', 'shoulders'],
	},
	{
		id: 18,
		name: 'Tuck Planche',
		description: 'Planche con rodillas recogidas. Equilibrio sobre las manos con el cuerpo elevado y rodillas al pecho.',
		image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
		difficulty: 4,
		muscle_group: ['shoulders', 'chest', 'core'],
	},
	{
		id: 19,
		name: 'Dragon Flag',
		description: 'Ejercicio avanzado de core. Acostado boca arriba, eleva las piernas y caderas manteniendo solo los hombros en contacto con el banco.',
		image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
		difficulty: 4,
		muscle_group: ['core'],
	},
	{
		id: 20,
		name: 'Hanging Leg Raise',
		description: 'Elevación de piernas colgado. Cuélgate de una barra y eleva las piernas rectas hasta formar un ángulo de 90 grados.',
		image: 'https://images.unsplash.com/photo-1597347316205-36f6c451902a?w=800&q=80',
		difficulty: 2,
		muscle_group: ['core'],
	},
];

// Old workout type for backwards compatibility
export const mockWorkouts: Workout[] = [
	{
		id: 1,
		owner: 1,
		likes: [],
		title: 'Rutina de Principiante',
		description: 'Rutina básica para empezar en calistenia',
		image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
		visible: true,
	},
	{
		id: 2,
		owner: 1,
		likes: [],
		title: 'Full Body Intermedio',
		description: 'Entrenamiento completo de cuerpo para nivel intermedio',
		image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
		visible: true,
	},
];

// New workout format with exercises for the workouts module
export const mockWorkoutDetails: WorkoutDetail[] = [
	{
		id: 1,
		name: 'Beginner Routine',
		description: 'Basic routine to start in calisthenics. Ideal for those taking their first steps in bodyweight training.',
		difficulty: 'Beginner',
		duration: 25,
		muscle_groups: ['chest', 'back', 'legs', 'core'],
		user_id: 'mock-user-1',
		tags: ['full-body', 'basic'],
		exercises: [
			{
				id: 'ex-1',
				exercise_id: 1,
				name: 'Push Up',
				sets: 3,
				reps: 10,
				rest: 60,
				muscle_group: ['chest', 'shoulders', 'triceps'],
			},
			{
				id: 'ex-2',
				exercise_id: 10,
				name: 'Australian Pull Up',
				sets: 3,
				reps: 10,
				rest: 60,
				muscle_group: ['back', 'biceps'],
			},
			{
				id: 'ex-3',
				exercise_id: 3,
				name: 'Squat',
				sets: 3,
				reps: 15,
				rest: 45,
				muscle_group: ['legs', 'glutes'],
			},
			{
				id: 'ex-4',
				exercise_id: 5,
				name: 'Plank',
				sets: 3,
				reps: 30,
				rest: 30,
				muscle_group: ['core', 'shoulders'],
			},
		],
	},
	{
		id: 2,
		name: 'Full Body Intermediate',
		description: 'Complete body workout for intermediate level. Includes more challenging exercises to keep progressing.',
		difficulty: 'Intermediate',
		duration: 40,
		muscle_groups: ['chest', 'back', 'triceps', 'biceps', 'legs', 'core'],
		user_id: 'mock-user-1',
		tags: ['full-body', 'strength'],
		exercises: [
			{
				id: 'ex-5',
				exercise_id: 11,
				name: 'Diamond Push Up',
				sets: 4,
				reps: 12,
				rest: 60,
				muscle_group: ['triceps', 'chest'],
			},
			{
				id: 'ex-6',
				exercise_id: 2,
				name: 'Pull Up',
				sets: 4,
				reps: 8,
				rest: 90,
				muscle_group: ['back', 'biceps'],
			},
			{
				id: 'ex-7',
				exercise_id: 4,
				name: 'Dips',
				sets: 4,
				reps: 10,
				rest: 60,
				muscle_group: ['triceps', 'chest', 'shoulders'],
			},
			{
				id: 'ex-8',
				exercise_id: 12,
				name: 'Chin Up',
				sets: 3,
				reps: 8,
				rest: 90,
				muscle_group: ['biceps', 'back'],
			},
			{
				id: 'ex-9',
				exercise_id: 3,
				name: 'Squat',
				sets: 4,
				reps: 20,
				rest: 45,
				muscle_group: ['legs', 'glutes'],
			},
			{
				id: 'ex-10',
				exercise_id: 20,
				name: 'Hanging Leg Raise',
				sets: 3,
				reps: 12,
				rest: 45,
				muscle_group: ['core'],
			},
		],
	},
	{
		id: 3,
		name: 'Advanced Push Day',
		description: 'Push day for advanced athletes. Focused on chest, shoulders and triceps with high intensity exercises.',
		difficulty: 'Advanced',
		duration: 50,
		muscle_groups: ['chest', 'shoulders', 'triceps', 'core'],
		user_id: 'mock-user-1',
		tags: ['push', 'upper-body'],
		exercises: [
			{
				id: 'ex-11',
				exercise_id: 8,
				name: 'Handstand Push Up',
				sets: 4,
				reps: 6,
				rest: 120,
				muscle_group: ['shoulders', 'triceps', 'core'],
			},
			{
				id: 'ex-12',
				exercise_id: 17,
				name: 'Archer Push Up',
				sets: 4,
				reps: 8,
				rest: 90,
				muscle_group: ['chest', 'triceps', 'shoulders'],
			},
			{
				id: 'ex-13',
				exercise_id: 4,
				name: 'Dips',
				sets: 4,
				reps: 15,
				rest: 60,
				muscle_group: ['triceps', 'chest', 'shoulders'],
			},
			{
				id: 'ex-14',
				exercise_id: 11,
				name: 'Diamond Push Up',
				sets: 3,
				reps: 15,
				rest: 45,
				muscle_group: ['triceps', 'chest'],
			},
			{
				id: 'ex-15',
				exercise_id: 18,
				name: 'Tuck Planche',
				sets: 4,
				reps: 15,
				rest: 90,
				muscle_group: ['shoulders', 'chest', 'core'],
			},
		],
	},
	{
		id: 4,
		name: 'Advanced Pull Day',
		description: 'Pull day for advanced athletes. Works back and biceps with high demand compound movements.',
		difficulty: 'Advanced',
		duration: 45,
		muscle_groups: ['back', 'biceps', 'core', 'shoulders'],
		user_id: 'mock-user-1',
		tags: ['pull', 'back'],
		exercises: [
			{
				id: 'ex-16',
				exercise_id: 6,
				name: 'Muscle Up',
				sets: 4,
				reps: 5,
				rest: 150,
				muscle_group: ['back', 'chest', 'triceps', 'shoulders'],
			},
			{
				id: 'ex-17',
				exercise_id: 2,
				name: 'Pull Up',
				sets: 4,
				reps: 12,
				rest: 90,
				muscle_group: ['back', 'biceps'],
			},
			{
				id: 'ex-18',
				exercise_id: 12,
				name: 'Chin Up',
				sets: 4,
				reps: 10,
				rest: 60,
				muscle_group: ['biceps', 'back'],
			},
			{
				id: 'ex-19',
				exercise_id: 14,
				name: 'Front Lever',
				sets: 4,
				reps: 10,
				rest: 120,
				muscle_group: ['back', 'core', 'shoulders'],
			},
		],
	},
	{
		id: 5,
		name: 'Core Destroyer',
		description: 'Intensive core routine. Strengthen your core with progressive exercises from intermediate to advanced.',
		difficulty: 'Intermediate',
		duration: 30,
		muscle_groups: ['core', 'shoulders'],
		user_id: 'mock-user-2',
		tags: ['core', 'abs'],
		exercises: [
			{
				id: 'ex-20',
				exercise_id: 20,
				name: 'Hanging Leg Raise',
				sets: 4,
				reps: 15,
				rest: 45,
				muscle_group: ['core'],
			},
			{
				id: 'ex-21',
				exercise_id: 9,
				name: 'L-Sit',
				sets: 4,
				reps: 20,
				rest: 60,
				muscle_group: ['core', 'triceps', 'shoulders'],
			},
			{
				id: 'ex-22',
				exercise_id: 5,
				name: 'Plank',
				sets: 3,
				reps: 60,
				rest: 30,
				muscle_group: ['core', 'shoulders'],
			},
			{
				id: 'ex-23',
				exercise_id: 19,
				name: 'Dragon Flag',
				sets: 3,
				reps: 8,
				rest: 90,
				muscle_group: ['core'],
			},
		],
	},
	{
		id: 6,
		name: 'Complete Leg Day',
		description: 'Complete leg routine using only bodyweight. From basic squats to pistol squats.',
		difficulty: 'Intermediate',
		duration: 35,
		muscle_groups: ['legs', 'glutes', 'core'],
		user_id: 'mock-user-2',
		tags: ['legs', 'lower-body'],
		exercises: [
			{
				id: 'ex-24',
				exercise_id: 3,
				name: 'Squat',
				sets: 4,
				reps: 20,
				rest: 45,
				muscle_group: ['legs', 'glutes'],
			},
			{
				id: 'ex-25',
				exercise_id: 7,
				name: 'Pistol Squat',
				sets: 3,
				reps: 5,
				rest: 90,
				muscle_group: ['legs', 'glutes', 'core'],
			},
			{
				id: 'ex-26',
				exercise_id: 13,
				name: 'Burpee',
				sets: 4,
				reps: 10,
				rest: 60,
				muscle_group: ['legs', 'chest', 'core', 'shoulders'],
			},
			{
				id: 'ex-27',
				exercise_id: 5,
				name: 'Plank',
				sets: 3,
				reps: 45,
				rest: 30,
				muscle_group: ['core', 'shoulders'],
			},
		],
	},
	{
		id: 7,
		name: 'Skills Workout',
		description: 'Workout focused on advanced calisthenics skills. For athletes who want to master static movements.',
		difficulty: 'Expert',
		duration: 60,
		muscle_groups: ['back', 'shoulders', 'core', 'chest'],
		user_id: 'mock-user-1',
		tags: ['skills', 'static'],
		exercises: [
			{
				id: 'ex-28',
				exercise_id: 14,
				name: 'Front Lever',
				sets: 5,
				reps: 15,
				rest: 150,
				muscle_group: ['back', 'core', 'shoulders'],
			},
			{
				id: 'ex-29',
				exercise_id: 15,
				name: 'Back Lever',
				sets: 4,
				reps: 15,
				rest: 120,
				muscle_group: ['shoulders', 'back', 'core'],
			},
			{
				id: 'ex-30',
				exercise_id: 18,
				name: 'Tuck Planche',
				sets: 5,
				reps: 15,
				rest: 120,
				muscle_group: ['shoulders', 'chest', 'core'],
			},
			{
				id: 'ex-31',
				exercise_id: 16,
				name: 'Human Flag',
				sets: 4,
				reps: 10,
				rest: 150,
				muscle_group: ['core', 'shoulders', 'back'],
			},
			{
				id: 'ex-32',
				exercise_id: 9,
				name: 'L-Sit',
				sets: 4,
				reps: 30,
				rest: 60,
				muscle_group: ['core', 'triceps', 'shoulders'],
			},
		],
	},
];

export const mockFilters = {
	muscle_group: ['chest', 'back', 'shoulders', 'triceps', 'biceps', 'core', 'legs', 'glutes'],
	difficulty: [0, 1, 2, 3, 4, 5],
};

export const mockWorkoutFilters = {
	difficulties: ['Beginner', 'Intermediate', 'Advanced', 'Expert'],
	muscleGroups: ['chest', 'back', 'shoulders', 'triceps', 'biceps', 'core', 'legs', 'glutes'],
	durations: [25, 30, 35, 40, 45, 50, 60],
	tags: ['full-body', 'push', 'pull', 'core', 'legs', 'skills', 'basic', 'strength', 'upper-body', 'back', 'abs', 'lower-body', 'static'],
};

export function isSupabaseConfigured(): boolean {
	return !!(
		process.env.NEXT_PUBLIC_SUPABASE_URL &&
		process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY &&
		process.env.NEXT_PUBLIC_SUPABASE_URL.startsWith('http')
	);
}
